More plugins! Add completion and a default chooser function.

diff --git a/choose b/choose
--- a/choose
+++ b/choose
@@ -1,5 +1,6 @@
 #!/bin/bash
 # choose - Line selection abstraction (plus utilities!)
+# Source this file to enable completion and expose internal functions.
 # Supported tools:
 #  dmenu    : https://tools.suckless.org/dmenu/
 #  fzf      : https://github.com/junegunn/fzf
@@ -10,6 +11,44 @@
 #  slmenu   : https://bitbucket.org/rafaelgg/slmenu
 #  vis-menu : https://github.com/martanne/vis
 # by Mike Lalumiere 2019
+
+chuz() {
+    # usage
+    read -r -d '' use <<EOF
+chuz < INPUT > LINE
+Select one line from input.
+EOF
+    # prepend a number to each line of input
+    local ind lines
+    mapfile -t lines
+    for ((ind=0; ind < "${#lines[@]}"; ind++)); do
+        printf "% 5d %s\n" "$ind" "${lines[$ind]}" >&2
+    done < <(printf "%s\n" "${lines[@]}")
+    # prompt interactively to select a line number
+    shopt -s nocasematch
+    while read -p "#? " -r sel < /dev/tty; do
+        if ! [[ "$sel" =~ ^[0-9]+$ ]]; then
+            # MAYBE tput reset >&2
+            # given a non-number perform a string search
+            for ((ind=0; ind < "${#lines[@]}"; ind++)); do
+                if [[ "${lines[$ind]}" =~ $sel ]]; then
+                    printf "% 5d %s\n" "$ind" "${lines[$ind]}" >&2
+                fi
+            done < <(printf "%s\n" "${lines[@]}")
+        else
+            # line number must be within boundaries
+            if [ "$sel" -lt "${#lines[@]}" ]; then
+                break
+            fi
+        fi
+    done
+    shopt -u nocasematch
+    # needs a selection
+    if [ -z "$sel" ]; then return 2; fi
+    # print the selected line
+    printf "%s\n" "${lines[$sel]}"
+}
+
 choose() {
     # usage
     read -r -d '' use <<EOF
@@ -41,9 +80,19 @@ Currently supported tools:
 EOF
     # some selection utils are graphical or terminal-only
     local gfx="${CHOOSE_GUI}"
+    # figure available graphical program
+    read -r -a gbins <<< "${CHOOSE_BINS_GUI:-dmenu rofi}"
+    for it in "${gbins[@]}"; do
+        if type "$it" &>/dev/null; then gbin="$it"; break; fi
+    done
+    # figure available terminal program
+    read -r -a tbins <<< "${CHOOSE_BINS_TTY:-fzf pick iselect slmenu vis-menu sentaku}"
+    for it in "${tbins[@]}"; do
+        if type "$it" &>/dev/null; then tbin="$it"; break; fi
+    done
     # accept options
     local opt OPTIND OPTARG
-    while getopts ":hlgt" opt; do
+    while getopts ":hlgqt" opt; do
         case "$opt" in
             g) # try to use a graphical program for line selection
                 gfx=1
@@ -57,6 +106,10 @@ EOF
                         printf "%s\n" "${f##choose_}"
                     fi
                 done < <(compgen -c) | sort
+                return 0
+                ;;
+            q) # list supported programs
+                printf "%s\n" "${gbins[@]}" "${tbins[@]}" | sort
                 return 0
                 ;;
             h) # write some help text
@@ -93,16 +146,6 @@ EOF
     fi
     # read stdin
     mapfile -t lines
-    # figure available graphical program
-    read -r -a gbins <<< "${CHOOSE_BINS_GUI:-dmenu rofi}"
-    for it in "${gbins[@]}"; do
-        if type "$it" &>/dev/null; then gbin="$it"; break; fi
-    done
-    # figure available terminal program
-    read -r -a tbins <<< "${CHOOSE_BINS_TTY:-fzf pick iselect slmenu vis-menu sentaku}"
-    for it in "${tbins[@]}"; do
-        if type "$it" &>/dev/null; then tbin="$it"; break; fi
-    done
     # using a util of the appropriate flavor...
     if ((gfx)); then app="$gbin"; else app="$tbin"; fi
     # choose a line
@@ -115,14 +158,22 @@ EOF
             rofi     ) rofi -dmenu -p "" ;;
             sentaku  ) sentaku -s $'\n' | head -n1 ;;
             slmenu   ) slmenu -i -l 30 ;;
-            vis-menu) vis-menu -i -l 30 ;;
-            *) printf "%s\n" "No tools available! These are supported:" >&2
-               printf "%s\n" "${tbins[@]}" "${gbins[@]}"
-               return 3
-               ;;
+            vis-menu ) vis-menu -i -l 30 ;;
+            *        ) chuz ;;
         esac
     return 0
 }
+
+####
+
+# command completion
+function _choose() {
+    local cur opts
+    cur="${COMP_WORDS[COMP_CWORD]}"
+    opts=$(printf -- "-%s " g h l q t)
+    COMPREPLY=($(compgen -W "$(choose -l) $opts" -- "$cur"))
+}
+complete -F _choose choose
 
 # choose meta
 choose_meta() {
@@ -168,7 +219,7 @@ choose_file() {
         # shell quote file names to fit on one line
         qot=$(printf "%q\n" "$that")
         files+=("$qot")
-    done < <(find "$dir" -type f -print0)
+    done < <(find "$dir" -maxdepth 5 -type f -print0)
     # choose one of them
     it=$(printf "%s\n"  "${files[@]}" | choose)
     if [[ -z "$it" ]]; then return 2; fi
@@ -193,7 +244,7 @@ choose_dir() {
         # shell quote file names to fit on one line
         qot=$(printf "%q\n" "$that")
         dirs+=("$qot")
-    done < <(find "$dir" -type d -print0)
+    done < <(find "$dir" -maxdepth 5 -type d -print0)
     # choose one of them
     it=$(printf "%s\n" "${dirs[@]}" | choose)
     if [[ -z "$it" ]]; then return 2; fi
@@ -387,12 +438,96 @@ choose_word() {
         printf "%s - Missing word file %s \n" "${FUNCNAME[0]}" "$dict" >&2
         return 1
     fi
-    # choose a word
+    # choose a word from the dictionary file
     local word
     word=$(choose < "$dict")
     if [[ -z "$word" ]]; then return 2; fi
     printf "%s\n" "$word"
 }
+
+# choose an active file used by git
+choose_git() {
+    # require find
+    if ! type git &>/dev/null; then
+        printf "%s - Missing git?\n" "${FUNCNAME[0]}" >&2
+        return 1
+    fi
+    # accept git working directory argument
+    local dir="${1:-.}"
+    if ! [ -d "$dir" ]; then
+        return 1
+    fi
+    # figure root of repository
+    local root
+    root=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null)
+    if [ -z "$root" ]; then
+        return 2
+    fi
+    # choose a file from the status list
+    local line
+    line=$(git -C "$dir" status -sbu | grep -v ^# | choose)
+    read -r _ file <<< "$line"
+    if [[ -z "$file" ]]; then return 2; fi
+    printf "%s/%s\n" "$root" "$file"
+}
+
+# choose corrections from input
+choose_ispell() {
+    # require ispell
+    if ! type ispell &>/dev/null; then
+        printf "%s - Missing git?\n" "${FUNCNAME[0]}" >&2
+        return 1
+    fi
+    # read input lines
+    mapfile -t lines
+    # parse ispell spellcheck output
+    local line="" index=0
+    while read -r symbol rest; do
+        # corrections are applied to lines in order
+        line="${lines[$index]}"
+        # each ispell output line is prefixed by a symbol
+        case "$symbol" in
+            '') # next
+                let index++
+                continue
+                ;;
+            '?') # guess
+                false ;;
+            '&') # miss
+                read -r bad _ _ sug   <<< "$rest"
+                IFS=', ' read -r -a fixes <<< "$sug"
+                fix=$(printf "%s\n" "${fixes[@]}" | choose)
+                if [ -n "$fix" ]; then
+                    lines["$index"]="${line/$bad/$fix}"
+                fi
+                ;;
+            '#') # no guess
+                continue
+                ;;
+            '*') # okay
+                continue
+                ;;
+            '+') # root
+                continue
+                ;;
+        esac
+    done < <(printf "%s\n" "${lines[@]}" | ispell -a)
+    printf "%s\n" "${lines[@]}"
+}
+
+# choose an ansible manual page to open
+choose_ansibledoc() {
+    # require ansible-doc
+    if ! type ansible-doc &>/dev/null; then
+        printf "%s\n Missing ansible-doc.\n" "${FUNCNAME[0]}" >&2
+        return 1
+    fi
+    # pick a page and read it
+    read -r page _ < <(ansible-doc -l | choose)
+    if [ -z "$page" ]; then return 2; fi
+    ansible-doc "$page"
+}
+
 
 # run it unless sourced
 if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then choose "$@"; fi
